name: DevOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      #  ESLint
      - name: Run ESLint
        run: npm run lint

      #  Jest + Coverage
      - name: Run Tests with Coverage
        run: npm run test:coverage

      #  SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      #  Build
      - name: Run Build
        run: npm run build

      #  Docker
      - name: Build Docker Image
        run: docker build -t devops-app .
